name: Build and Test NODE
on: [pull_request, workflow_dispatch, push]
jobs:
  build-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [24]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v5
        with:
          version: 10.33.0

      - name: 'Setup node with cache'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test:ci

      - name: 'Upload coverage reports'
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
